with 

source as (

    select 
        *,
        
        array_sort(array_construct(team, opponent_team)) as team_key_array,        
        concat(team_key_array[0], '-', team_key_array[1], '_', date) as serie_key
    from {{ source('matchstats', 'matchstats') }}

),

renamed as (

    select
        serie_key,
        {{dbt_utils.generate_surrogate_key(['serie_key'])}} as id_serie,
        {{dbt_utils.generate_surrogate_key(['no_game', 'game_of_day', 'date'])}} as id_game,
        {{dbt_utils.generate_surrogate_key(['player'])}} as id_player,
        player::varchar(50) as player_name,        
        role,
        {{dbt_utils.generate_surrogate_key(['team'])}} as id_team,
        team as team_name,
        opponent_team as opponent_team_name,
        {{dbt_utils.generate_surrogate_key(['opponent_team'])}} as id_opponent_team,
        opponent_player as opponent_player_name,
        CONVERT_TIMEZONE('UTC', date) AS date,
        {{dbt_utils.generate_surrogate_key(['id_game', 'id_team'])}} as id_game_team_stats,        
        round,
        day as day_of_match,
        patch,
        stage,
        no_game as game_number,
        all_games as total_games_match,
        format as match_format,
        game_of_day,
        side,
        time as game_duration,
        {{dbt_utils.generate_surrogate_key(['ban'])}} as id_ban,
        ban,
        ban_opponent,
        {{dbt_utils.generate_surrogate_key(['ban_opponent'])}} as id_opponent_ban,
        {{dbt_utils.generate_surrogate_key(['pick'])}} as id_pick,
        pick,
        pick_opponent,
        {{dbt_utils.generate_surrogate_key(['champion'])}} as id_champion,
        champion,
        champion_opponent,
        outcome,
        kills_team,
        turrets_team,
        dragon_team,
        baron_team,
        level,
        kills,
        deaths,
        assists,
        --IFF(kda = 'Perfect_KDA', kda = '99', kda) as kda,
        cs,
        cs_in_team_s_jungle,
        cs_in_enemy_jungle,
        csm as cs_per_minute,
        golds as player_gold,
        gpm as gold_per_minute,
        gold_percent,
        vision_score,
        wards_placed,
        wards_destroyed,
        control_wards_purchased,
        detector_wards_placed,
        vspm as vision_score_per_minute,
        wpm as wards_placed_per_minute,
        vwpm as vision_wards_placed_per_minute,
        wcpm as control_wards_placed_per_minute,
        vs_percent as vision_score_percent,
        total_damage_to_champion,
        physical_damage,
        magic_damage,
        true_damage,
        dpm as damage_per_minute,
        dmg_percent as damage_percent,
        k_plus_a_per_minute as kills_plus_assits_per_minute,
        kp_percent as kill_participation,
        solo_kills,
        double_kills,
        triple_kills,
        quadra_kills,
        penta_kills,
        gd_at_15 as gold_difference_at_15,
        csd_at_15 as cs_difference_at_15,
        xpd_at_15 as xp_difference_at_15,
        lvld_at_15 as level_difference_at_15,
        objectives_stolen,
        damage_dealt_to_turrets,
        damage_dealt_to_buildings,
        total_heal,
        total_heals_on_teammates,
        damage_self_mitigated,
        total_damage_shielded_on_teammates,
        time_ccing_others,
        total_time_cc_dealt,
        total_damage_taken,
        total_time_spent_dead,
        consumables_purchased,
        items_purchased,
        shutdown_bounty_collected,
        shutdown_bounty_lost,
        date_load
    from source

)

select * from renamed
